//! Terrain-tile texture-array packing for the ADT loader.
//!
//! A tile's ground textures are stacked into one repeating, mipmapped `texture_2d_array`; its
//! per-chunk alpha (blend-weight) and MCSH shadow maps into two more arrays. The fidelity-critical
//! rule (the "C2" invariant, anchored in `wow-5875-re/system/terrain`): the BLP's **authored** mip
//! pyramid is laid in **verbatim** — never CPU-regenerated by averaging texels in gamma byte space,
//! which darkens mid-tones and cools foliage. Off-Elwynn BLPs authored below [`LAYER_TEX_SIZE`] fill
//! the top mips by `NEAREST` upsample (texel replication — gamma-safe, no averaging).

use benilla_formats::BlpMipChain;
use bevy::asset::RenderAssetUsages;
use bevy::image::{Image, ImageAddressMode, ImageFilterMode, ImageSampler, ImageSamplerDescriptor};
use bevy::prelude::*;
use bevy::render::render_resource::{
    Extent3d, TextureDataOrder, TextureDimension, TextureFormat, TextureViewDescriptor,
    TextureViewDimension,
};

/// Edge length every layer BLP is uploaded at for the per-tile array (uniform so they share one
/// `texture_2d_array`). The Elwynn A/B target's layer BLPs are all natively 256² with 8 authored mips.
pub(crate) const LAYER_TEX_SIZE: u32 = 256;

/// Per-layer mip count for the array — the authored count at 256². Fewer-mip BLPs repeat the last
/// authored level; sub-256² BLPs upsample (NEAREST) to fill the top.
pub(crate) const LAYER_MIP_COUNT: u32 = 8;

/// Albedo format: non-sRGB `Rgba8Unorm` — the GPU does not linearize on sample, so shader math stays
/// in WoW's gamma/byte space (the RE'd invariant; matches the model/BLP albedo format).
fn color_format() -> TextureFormat {
    TextureFormat::Rgba8Unorm
}

/// One ground texture packed for the per-tile array: its authored mip chain at [`LAYER_TEX_SIZE`]²,
/// concatenated mip-major (level 0 first), `mip_count` levels.
pub(crate) struct LayerTexture {
    pub(crate) chain: Vec<u8>,
    pub(crate) mip_count: u32,
}

/// Pack a BLP's authored mip pyramid into a [`LayerTexture`] for the tile array — authored levels
/// used verbatim (the C2 fix). When the BLP's mip 0 is smaller than `target_size` (off-Elwynn) the
/// top of the chain is NEAREST-upsampled (texel replication, gamma-safe), with the BLP's authored
/// smaller mips slotting into the deeper array levels; when its chain runs out the last authored mip
/// is reused (NEAREST-resampled if the dims still differ).
pub(crate) fn chain_to_layer(blp: BlpMipChain, target_size: u32) -> LayerTexture {
    // **This lane cannot take DXT blocks and must not be handed them.** It NEAREST-resamples levels
    // to a uniform array size and its caller stomps the alpha byte for the matte case — both are
    // per-texel CPU writes, which is exactly what a block form does not have. So terrain layers
    // stay decoded while model/WMO albedo passes through (decision 1626); the day this lane wants
    // the same win, the resample and the alpha stomp are what have to go first.
    debug_assert!(
        blp.is_rgba8(),
        "terrain layer packing indexes texels; it needs a decoded chain"
    );
    let mut chain = Vec::with_capacity(mip_chain_byte_size(target_size, LAYER_MIP_COUNT));
    for level in 0..LAYER_MIP_COUNT {
        let level_w = (target_size >> level).max(1);
        let level_h = level_w; // tilesets are square in 1.12
        if blp.width >= level_w {
            // `BLP width >> j == level_w`  ⟹  `j = log2(BLP width / level_w)`, clamped to the BLP's
            // available mips (if it doesn't go that deep, repeat the last authored level).
            let ratio = (blp.width / level_w).max(1);
            let src_level = (ratio.trailing_zeros() as usize).min(blp.mips.len() - 1);
            let (sw, sh) = blp.mip_size(src_level as u32);
            extend_nearest(&mut chain, &blp.mips[src_level], sw, sh, level_w, level_h);
        } else {
            // Authored smaller than this level — NEAREST-upsample mip 0 (texel replication).
            extend_nearest(
                &mut chain,
                &blp.mips[0],
                blp.width,
                blp.height,
                level_w,
                level_h,
            );
        }
    }
    LayerTexture {
        chain,
        mip_count: LAYER_MIP_COUNT,
    }
}

/// A solid-colour layer chain at [`LAYER_TEX_SIZE`]² with [`LAYER_MIP_COUNT`] levels — the per-tile
/// array's fallback layer 0 (a solid colour downsamples to itself, so every mip is the same colour).
pub(crate) fn solid_layer_chain(rgba: [u8; 4]) -> LayerTexture {
    let mut chain = Vec::with_capacity(mip_chain_byte_size(LAYER_TEX_SIZE, LAYER_MIP_COUNT));
    for level in 0..LAYER_MIP_COUNT {
        let w = (LAYER_TEX_SIZE >> level).max(1);
        for _ in 0..(w * w) {
            chain.extend_from_slice(&rgba);
        }
    }
    LayerTexture {
        chain,
        mip_count: LAYER_MIP_COUNT,
    }
}

/// Total bytes for a mip pyramid of `mip_count` levels starting at `top²` RGBA8.
pub(crate) fn mip_chain_byte_size(top: u32, mip_count: u32) -> usize {
    (0..mip_count)
        .map(|i| {
            let w = (top >> i).max(1);
            (w * w * 4) as usize
        })
        .sum()
}

/// Append `src` (RGBA8 `sw × sh`) resized to `dw × dh` to `out` using `NEAREST` — pure texel
/// replication/decimation, so gamma-encoded bytes pass through unchanged (no averaging → no
/// darkening). Identity at `(sw, sh) == (dw, dh)`.
pub(crate) fn extend_nearest(out: &mut Vec<u8>, src: &[u8], sw: u32, sh: u32, dw: u32, dh: u32) {
    if sw == dw && sh == dh {
        out.extend_from_slice(src);
        return;
    }
    let Some(buf) = image::RgbaImage::from_raw(sw, sh, src.to_vec()) else {
        out.extend(std::iter::repeat_n(0u8, (dw * dh * 4) as usize));
        return;
    };
    let resized = image::imageops::resize(&buf, dw, dh, image::imageops::FilterType::Nearest);
    out.extend_from_slice(resized.as_raw());
}

/// Stack the tile's ground textures into a repeating, mipmapped `2d_array`. `rgba` holds each layer's
/// full `mip_levels`-deep chain (LayerMajor order); `layer_count` layers at `size²` mip 0.
pub(crate) fn layer_array_image(
    size: u32,
    layer_count: u32,
    mip_levels: u32,
    rgba: Vec<u8>,
) -> Image {
    // Image::new asserts mip-0 length; seed a correctly-sized buffer, then swap in the full chain.
    let mip0_len = (size * size * 4 * layer_count) as usize;
    let mut image = array_image(size, layer_count, vec![0u8; mip0_len], color_format());
    image.data = Some(rgba);
    image.texture_descriptor.mip_level_count = mip_levels;
    image.data_order = TextureDataOrder::LayerMajor;
    // Ground is the surface the filter policy costs the most on — a tiling texture at a grazing
    // angle is the anisotropy axis's worst case, and it fills most of the frame. The reference
    // does not let this lane choose: both values come from the process globals
    // ([`crate::tex_filter`]) — trilinear with anisotropy off, which is what `hwDetect` hands a
    // virgin install (1645).
    let filter = crate::tex_filter::tex_filter();
    image.sampler = ImageSampler::Descriptor(ImageSamplerDescriptor {
        address_mode_u: ImageAddressMode::Repeat,
        address_mode_v: ImageAddressMode::Repeat,
        mag_filter: ImageFilterMode::Linear,
        min_filter: ImageFilterMode::Linear,
        mipmap_filter: filter.mipmap_filter(),
        anisotropy_clamp: filter.anisotropy_clamp(),
        ..default()
    });
    image
}

/// Stack `layer_count` per-chunk alpha maps (each `size²`, concatenated) into a linear `2d_array` —
/// the tile's blend weights (R/G/B = layers 1/2/3 opacity). Non-colour, so `Rgba8Unorm`.
pub(crate) fn alpha_array_image(size: u32, layer_count: u32, rgba: Vec<u8>) -> Image {
    array_image(size, layer_count, rgba, TextureFormat::Rgba8Unorm)
}

/// Stack `layer_count` MCSH shadow maps (each `size²`, one byte/texel) into a single-channel
/// `2d_array` — WoW's pre-baked static terrain shadows (`R` = shadowed, 0 = lit).
pub(crate) fn shadow_array_image(size: u32, layer_count: u32, data: Vec<u8>) -> Image {
    array_image(size, layer_count, data, TextureFormat::R8Unorm)
}

/// Build a `2d_array` `Image` from concatenated per-layer bytes, with a `D2Array` view so the
/// `dimension = "2d_array"` bindings resolve.
///
/// `RenderAssetUsages::RENDER_WORLD`: the render world takes the bytes on extract — a tile's
/// three arrays are megabytes each, and nothing reads them main-side (they flow into the terrain
/// material as handles; the minimap, collider, clutter all derive from other sources). The
/// default usage cloned every array on landing AND kept a main-world copy resident per tile —
/// pure cost on both the B181 landing frame and the resident-set memory.
fn array_image(size: u32, layer_count: u32, data: Vec<u8>, format: TextureFormat) -> Image {
    let mut image = Image::new(
        Extent3d {
            width: size,
            height: size,
            depth_or_array_layers: layer_count,
        },
        TextureDimension::D2,
        data,
        format,
        RenderAssetUsages::RENDER_WORLD,
    );
    image.texture_view_descriptor = Some(TextureViewDescriptor {
        dimension: Some(TextureViewDimension::D2Array),
        ..default()
    });
    image
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A synthetic BLP mip chain: `mips` authored levels of a solid grey fill at `size²`.
    fn synthetic_chain(size: u32, mips: u32) -> BlpMipChain {
        let levels = (0..mips)
            .map(|i| {
                let w = (size >> i).max(1);
                vec![200u8; (w * w * 4) as usize]
            })
            .collect();
        BlpMipChain {
            texels: benilla_formats::BlpTexels::Rgba8Unorm,
            width: size,
            height: size,
            mips: levels,
        }
    }

    #[test]
    fn chain_to_layer_packs_a_native_256_blp_to_the_full_chain() {
        let layer = chain_to_layer(synthetic_chain(256, 8), LAYER_TEX_SIZE);
        assert_eq!(layer.mip_count, LAYER_MIP_COUNT);
        assert_eq!(
            layer.chain.len(),
            mip_chain_byte_size(LAYER_TEX_SIZE, LAYER_MIP_COUNT)
        );
    }

    #[test]
    fn chain_to_layer_upsamples_a_small_blp_without_darkening() {
        // A 64² BLP packed to 256²: the top levels are NEAREST-upsampled. A solid 200 in must come
        // out solid 200 — averaging (the C2 bug) would dim it below 200.
        let layer = chain_to_layer(synthetic_chain(64, 7), 256);
        assert_eq!(layer.chain.len(), mip_chain_byte_size(256, LAYER_MIP_COUNT));
        assert!(
            layer.chain.iter().all(|&b| b == 200),
            "NEAREST upsample must preserve the authored gamma bytes (no averaging)"
        );
    }

    #[test]
    fn solid_layer_chain_is_one_colour_at_every_mip() {
        let layer = solid_layer_chain([10, 20, 30, 40]);
        assert_eq!(
            layer.chain.len(),
            mip_chain_byte_size(LAYER_TEX_SIZE, LAYER_MIP_COUNT)
        );
        assert!(layer.chain.chunks_exact(4).all(|px| px == [10, 20, 30, 40]));
    }

    #[test]
    fn layer_array_image_has_the_expected_shape() {
        let bytes = vec![0u8; 3 * mip_chain_byte_size(LAYER_TEX_SIZE, LAYER_MIP_COUNT)];
        let img = layer_array_image(LAYER_TEX_SIZE, 3, LAYER_MIP_COUNT, bytes);
        assert_eq!(img.texture_descriptor.size.width, LAYER_TEX_SIZE);
        assert_eq!(img.texture_descriptor.size.depth_or_array_layers, 3);
        assert_eq!(img.texture_descriptor.mip_level_count, LAYER_MIP_COUNT);
    }

    #[test]
    fn alpha_and_shadow_arrays_have_the_expected_shape_and_format() {
        let alpha = alpha_array_image(64, 2, vec![0u8; 2 * 64 * 64 * 4]);
        assert_eq!(alpha.texture_descriptor.size.depth_or_array_layers, 2);
        assert_eq!(alpha.texture_descriptor.format, TextureFormat::Rgba8Unorm);
        let shadow = shadow_array_image(64, 2, vec![0u8; 2 * 64 * 64]);
        assert_eq!(shadow.texture_descriptor.size.depth_or_array_layers, 2);
        assert_eq!(shadow.texture_descriptor.format, TextureFormat::R8Unorm);
    }
}
