//! The preset files (`presets/*.toml`), compiled in. They are generated by
//! `scripts/gen-realm-presets.py` from a world database, so the service itself never needs one.

use std::sync::OnceLock;

use anyhow::{bail, Context, Result};
use serde::Deserialize;

#[derive(Debug, Clone, Deserialize)]
pub struct Preset {
    pub id: String,
    pub name: String,
    pub blurb: String,
    pub level: u8,
    /// A `game_tele` name at the instance entrance.
    pub tele: String,
    /// Copper each character starts with.
    pub money: u32,
    pub slots: Vec<Slot>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Slot {
    /// The class as the card shows it ("Warrior").
    pub label: String,
    /// The group role as the card shows it ("Tank").
    pub role: String,
    pub class: u8,
    pub race: u8,
    pub gender: u8,
    /// Class spells up to the preset level, learned with `.learn`.
    pub spells: Vec<u32>,
    /// Armor and weapon skills the gear needs; without them the server mails the item back.
    pub proficiencies: Vec<u32>,
    /// The rank spell of each talent pick, summing to `level - 9` points.
    pub talents: Vec<u32>,
    pub bags: Vec<u32>,
    /// One item per equipment slot (two rings take two entries).
    pub gear: Vec<u32>,
    /// `[item, count]`, left in the bags.
    pub consumables: Vec<(u32, u32)>,
}

const FILES: &[(&str, &str)] = &[
    ("deadmines", include_str!("../../presets/deadmines.toml")),
    ("brd", include_str!("../../presets/brd.toml")),
];

fn parse() -> Result<Vec<Preset>> {
    let mut out = Vec::new();
    for (file, text) in FILES {
        let p: Preset = toml::from_str(text).with_context(|| format!("presets/{file}.toml"))?;
        if p.id != *file {
            bail!("presets/{file}.toml says id = {:?}", p.id);
        }
        if p.slots.is_empty() || p.slots.len() > 40 {
            bail!("presets/{file}.toml: {} slots", p.slots.len());
        }
        if !(1..=60).contains(&p.level) {
            bail!("presets/{file}.toml: level {}", p.level);
        }
        crate::soap::arg(&p.tele, 64).with_context(|| format!("presets/{file}.toml: tele"))?;
        out.push(p);
    }
    Ok(out)
}

/// Every preset, in menu order.
pub fn all() -> &'static [Preset] {
    static ALL: OnceLock<Vec<Preset>> = OnceLock::new();
    ALL.get_or_init(|| parse().expect("the compiled-in presets parse (tested)"))
}

pub fn get(id: &str) -> Option<&'static Preset> {
    all().iter().find(|p| p.id == id)
}

pub fn class_name(class: u8) -> &'static str {
    crate::realmdb::class_name(i64::from(class))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn presets_parse_and_are_complete() {
        let all = parse().unwrap();
        assert_eq!(
            all.iter().map(|p| p.id.as_str()).collect::<Vec<_>>(),
            ["deadmines", "brd"]
        );
        for p in &all {
            for s in &p.slots {
                let at = format!("{}/{}", p.id, s.label);
                assert!(!s.spells.is_empty(), "{at}: no spells");
                assert!(s.gear.len() >= 10, "{at}: only {} gear items", s.gear.len());
                assert!((3..=4).contains(&s.bags.len()), "{at}: bags");
                assert!(!s.talents.is_empty(), "{at}: no talents");
                assert!(
                    matches!(s.race, 1 | 3 | 4 | 7),
                    "{at}: not an Alliance race"
                );
                assert!(s.gender <= 1, "{at}: gender");
                assert_ne!(class_name(s.class), "?", "{at}: class {}", s.class);
            }
        }
    }
}
