#!/usr/bin/env python3
r"""Generate `crates/benilla-ui/src/messages/catalog.rs` from wow-5875-re's message-catalog.tsv.

The TSV is the sibling repo's byte-exact sweep of build 5875's `0xb4b498` registry -- the table
`CGGameUI::DisplayError 0x496720` indexes by message id.  It is *their* artifact (regenerated there
with `re/ui/extract-message-catalog.py`); this script only re-shapes it into a Rust const, so the
table ships with benilla instead of being re-read out of a sibling checkout at build time.

    python3 scripts/gen-message-catalog.py ../wow-5875-re/re/ui/message-catalog.tsv

Refuses rather than emits on anything it does not understand: a non-dense id range, a duplicate key,
an unknown kind.  A generated table that quietly dropped a row would be worse than no table.
"""
import sys

KINDS = {0: "Chat", 1: "Info", 2: "Error"}

HEADER = """\
//! The 5875 message catalog, row for row.
//!
//! @generated by `scripts/gen-message-catalog.py` from wow-5875-re `re/ui/message-catalog.tsv`
//! (itself generated by that repo's `re/ui/extract-message-catalog.py` out of `WoW.exe`).
//! Do not edit by hand — regenerate.

use super::{MessageRecord, MsgKind};

/// Every row of `0xb4b498`, indexed by message id (the ids are dense `0..465`, so
/// `CATALOG[id]` *is* the reference's `0xb4b498 + 20*id`).
///
/// `rustfmt` is held off so that a regeneration is a no-op diff: one row per line is the shape
/// this script emits, and a formatter that rewrapped it would make the file drift from its own
/// generator.
#[rustfmt::skip]
pub static CATALOG: [MessageRecord; {count}] = [
"""


def main(path: str) -> int:
    rows = []
    for line in open(path):
        if line.startswith("#") or line.startswith("id_hex"):
            continue
        f = line.rstrip("\n").split("\t")
        if len(f) != 8:
            raise SystemExit(f"malformed row (expected 8 fields, got {len(f)}): {line!r}")
        rows.append(
            {
                "id": int(f[1]),
                "key": f[3],
                "kind": int(f[4]),
                "sound": f[5],
                "type_tag": int(f[6], 16),
                "chat_type": int(f[7]),
            }
        )

    for want, r in enumerate(rows):
        if r["id"] != want:
            raise SystemExit(f"ids are not dense: expected {want}, got {r['id']}")
    keys = [r["key"] for r in rows]
    if len(set(keys)) != len(keys):
        raise SystemExit("duplicate key in the catalog — by_key would be ambiguous")
    for r in rows:
        if r["kind"] not in KINDS:
            raise SystemExit(
                f"row {r['id']} ({r['key']}) has kind {r['kind']}, which MsgKind does not model"
            )

    out = [HEADER.replace("{count}", str(len(rows)))]
    for r in rows:
        sound = "None" if r["sound"] == "NONE" else f'Some("{r["sound"]}")'
        out.append(
            f'    MessageRecord {{ id: {r["id"]}, key: "{r["key"]}", '
            f'kind: MsgKind::{KINDS[r["kind"]]}, sound: {sound}, '
            f'type_tag: {r["type_tag"]:#04x}, chat_type: {r["chat_type"]} }},\n'
        )
    out.append("];\n")
    sys.stdout.write("".join(out))
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    sys.exit(main(sys.argv[1]))
